### PR TITLE
Add user's SuperSaaS plugin settings logging to improve troubleshooting

### PR DESCRIPTION
**Pull request by Plotist**
Log example: 
image

### CODE REVIEW

**Comment by Plotist** [comment]
@Fjan if I understand correctly [complete](http://api.jquery.com/ajaxComplete/) here **is** fired alongside [success](http://api.jquery.com/ajaxSuccess-shorthand/) and [error](http://api.jquery.com/ajaxError-shorthand/) regardless of the outcome.

**Comment by Plotist** [comment]
@Fjan discard my last comment, I got your concern

**Comment by Plotist** [comment]
@Fjan I'm gonna try and do just as per your recommendation and I also want to add something ENV dependent in order to avoid flooding logs with requests from locally running instances

**Comment by Fjan** [comment]
Ah, ok, `complete` may be good enough then. I'm not overly worried about locally running instances unless you see an easy way to prevent that.

**Review by Fjan — APPROVED** [review]

**Pull request merged**
